# Generated by Django 3.2 on 2022-02-18 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='client',
            field=models.ForeignKey(blank=True, default='', help_text='Client you are working for', on_delete=django.db.models.deletion.CASCADE, related_name='employee_requests_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
