# Generated by Django 3.2 on 2022-02-18 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='client',
            field=models.ForeignKey(blank=True, default='', help_text='Client you are working for', on_delete=django.db.models.deletion.CASCADE, related_name='employee_requests_created', to='employee.client'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='reporting_to',
            field=models.CharField(choices=[('Select', 'Select'), ('Akshay', 'Akshay'), ('Avni', 'Anvi'), ('Sandeep', 'Sandeep')], default='Select', help_text='your reporting manager', max_length=20, null=True, verbose_name='Reporting to'),
        ),
    ]
