# Generated by Django 3.2 on 2022-02-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20220218_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(blank=True, help_text='upload image size less than 2.0MB', null=True, upload_to='profiles', verbose_name='Profile Image'),
        ),
    ]
